import { validateFrameTemplate } from '@/features/frames/schema';

const RAW_SYSTEM_TEMPLATES = [
  {
    id: 'clean-ivory',
    name: 'Clean Ivory',
    description: 'Soft ivory, fine lines, and timeless typography.',
    canvas: { width: 1080, height: 1440 },
    background: { color: '#f4efe5' },
    photoSlots: [
      {
        id: 'portrait',
        kind: 'photo',
        x: 72,
        y: 72,
        width: 936,
        height: 1120,
        zIndex: 10,
      },
    ],
    elements: [
      {
        id: 'photo-line',
        kind: 'border',
        x: 58,
        y: 58,
        width: 964,
        height: 1148,
        zIndex: 20,
        color: '#a88c62',
        lineWidth: 2,
      },
      {
        id: 'event',
        kind: 'text',
        x: 90,
        y: 1240,
        width: 900,
        height: 76,
        zIndex: 30,
        content: 'event-name',
        color: '#332d27',
        fontFamily: 'serif',
        fontSize: 46,
        fontWeight: 600,
        lineHeight: 54,
        maxLines: 1,
        align: 'center',
      },
      {
        id: 'brand',
        kind: 'text',
        x: 90,
        y: 1336,
        width: 900,
        height: 32,
        zIndex: 30,
        content: 'brand',
        color: '#766858',
        fontFamily: 'sans-serif',
        fontSize: 20,
        fontWeight: 600,
        lineHeight: 24,
        maxLines: 1,
        align: 'center',
      },
    ],
  },
  {
    id: 'midnight-celebration',
    name: 'Midnight Celebration',
    description: 'Deep charcoal with a restrained champagne accent.',
    canvas: { width: 1080, height: 1440 },
    background: { color: '#171614' },
    photoSlots: [
      {
        id: 'portrait',
        kind: 'photo',
        x: 70,
        y: 170,
        width: 940,
        height: 1120,
        zIndex: 10,
        cornerRadius: 8,
      },
    ],
    elements: [
      {
        id: 'top-rule',
        kind: 'shape',
        x: 70,
        y: 94,
        width: 94,
        height: 4,
        zIndex: 20,
        fill: '#d8b16d',
      },
      {
        id: 'event',
        kind: 'text',
        x: 190,
        y: 68,
        width: 820,
        height: 70,
        zIndex: 30,
        content: 'event-name',
        color: '#f4e7cf',
        fontFamily: 'serif',
        fontSize: 42,
        fontWeight: 600,
        lineHeight: 50,
        maxLines: 1,
        align: 'right',
      },
      {
        id: 'brand',
        kind: 'text',
        x: 70,
        y: 1340,
        width: 940,
        height: 34,
        zIndex: 30,
        content: 'brand',
        color: '#cbb58e',
        fontFamily: 'sans-serif',
        fontSize: 20,
        fontWeight: 600,
        lineHeight: 24,
        maxLines: 1,
        align: 'left',
      },
    ],
  },
  {
    id: 'warm-editorial',
    name: 'Warm Editorial',
    description: 'A composed, magazine-inspired warm neutral layout.',
    canvas: { width: 1080, height: 1440 },
    background: { color: '#c9b49c' },
    photoSlots: [
      {
        id: 'portrait',
        kind: 'photo',
        x: 190,
        y: 90,
        width: 820,
        height: 1094,
        zIndex: 10,
      },
    ],
    elements: [
      {
        id: 'side-panel',
        kind: 'shape',
        x: 0,
        y: 0,
        width: 148,
        height: 1440,
        zIndex: 20,
        fill: '#3d352e',
      },
      {
        id: 'edition',
        kind: 'text',
        x: 34,
        y: 90,
        width: 80,
        height: 580,
        zIndex: 30,
        rotation: -90,
        content: 'literal',
        value: 'A MOMENT TO KEEP',
        color: '#f1e6d7',
        fontFamily: 'sans-serif',
        fontSize: 22,
        fontWeight: 600,
        lineHeight: 28,
        maxLines: 1,
        align: 'center',
      },
      {
        id: 'event',
        kind: 'text',
        x: 190,
        y: 1230,
        width: 820,
        height: 86,
        zIndex: 30,
        content: 'event-name',
        color: '#302923',
        fontFamily: 'serif',
        fontSize: 48,
        fontWeight: 600,
        lineHeight: 56,
        maxLines: 1,
        align: 'left',
      },
      {
        id: 'brand',
        kind: 'text',
        x: 190,
        y: 1342,
        width: 820,
        height: 30,
        zIndex: 30,
        content: 'brand',
        color: '#5e5044',
        fontFamily: 'sans-serif',
        fontSize: 19,
        fontWeight: 600,
        lineHeight: 24,
        maxLines: 1,
        align: 'left',
      },
    ],
  },
] as const;

export const SYSTEM_FRAME_TEMPLATES = RAW_SYSTEM_TEMPLATES.map((template) =>
  validateFrameTemplate(template),
);

export const DEFAULT_FRAME_TEMPLATE = SYSTEM_FRAME_TEMPLATES[0]!;
